Global:
  n_nodes:
    min: 3
    max: 5000
simu_short3-9_0-10:
  n_nodes:
    min: 3
    max: 9
  n_edges:
    min: 0
    max: 10
simu_short3-9_10-14:
  n_nodes:
    min: 3
    max: 9
  n_edges:
    min: 10
    max: 14
simu_short3-9_14-18:
  n_nodes:
    min: 3
    max: 9
  n_edges:
    min: 14
    max: 18
simu_short3-9_18:
  n_nodes:
    min: 3
    max: 9
  n_edges:
    min: 18
simu_short10-49_0-56:
  n_nodes:
    min: 10
    max: 49
  n_edges:
    min: 0
    max: 56
simu_short10-49_56-94:
  n_nodes:
    min: 10
    max: 49
  n_edges:
    min: 56
    max: 94
simu_short10-49_94-171:
  n_nodes:
    min: 10
    max: 49
  n_edges:
    min: 94
    max: 171
simu_short10-49_171:
  n_nodes:
    min: 10
    max: 49
  n_edges:
    min: 171
simu_short50-99_0-469:
  n_nodes:
    min: 50
    max: 99
  n_edges:
    min: 0
    max: 469
simu_short50-99_469-624:
  n_nodes:
    min: 50
    max: 99
  n_edges:
    min: 469
    max: 624
simu_short50-99_624-833:
  n_nodes:
    min: 50
    max: 99
  n_edges:
    min: 624
    max: 833
simu_short50-99_833:
  n_nodes:
    min: 50
    max: 99
  n_edges:
    min: 833
simu_short100-199_0-1184:
  n_nodes:
    min: 100
    max: 199
  n_edges:
    min: 0
    max: 1184
simu_short100-199_1184-1539:
  n_nodes:
    min: 100
    max: 199
  n_edges:
    min: 1184
    max: 1539
simu_short100-199_1539-1998:
  n_nodes:
    min: 100
    max: 199
  n_edges:
    min: 1539
    max: 1998
simu_short100-199_1998:
  n_nodes:
    min: 100
    max: 199
  n_edges:
    min: 1998
simu_short200-499_0-3006:
  n_nodes:
    min: 200
    max: 499
  n_edges:
    min: 0
    max: 3006
simu_short200-499_3006-3748:
  n_nodes:
    min: 200
    max: 499
  n_edges:
    min: 3006
    max: 3748
simu_short200-499_3748-4848:
  n_nodes:
    min: 200
    max: 499
  n_edges:
    min: 3748
    max: 4848
simu_short200-499_4848:
  n_nodes:
    min: 200
    max: 499
  n_edges:
    min: 4848
simu_short500-5000_0-10010:
  n_nodes:
    min: 500
    max: 5000
  n_edges:
    min: 0
    max: 10010
simu_short500-5000_10010-12975:
  n_nodes:
    min: 500
    max: 5000
  n_edges:
    min: 10010
    max: 12975
simu_short500-5000_12975-19987:
  n_nodes:
    min: 500
    max: 5000
  n_edges:
    min: 12975
    max: 19987
simu_short500-5000_19987:
  n_nodes:
    min: 500
    max: 5000
  n_edges:
    min: 19987
shuffle: False
